### ISSUE TITLE
Maintain symbolic expressions containing error for path conditions

### ISSUE THREAD

**Issue by Himeshi** [fp-analysis/klee#47]
If a path condition involves a symbolic input for which error is tracked, store the path condition with error.

If a path condition is computed using a symbolic input for which the error is tracked, obtain path condition with propagated error and store it.

**Comment by domainexpert** [comment]
@Himeshi I agree with this, since the input values in the error expression should be constrained by the path condition. This is probably entails a simple modification to `SpecialFunctionHandler::handleBoundError()` and `SymbolicError::outputErrorBound()`, where `state.constraints` need to be propagated to the `SymbolicError::outputErrorBound()`.

**Comment by domainexpert** [comment]
@Himeshi Just to add a note that as discussed in the meeting, I misunderstood the issue. The issue was there was a worry that the path condition does not contain error.

I believe it does. The current implementation of path condition (as is done in KLEE), is under the assumption that the numeric values in the program contains error. This is because the symbolic execution in KLEE is bit precise, which considers even overflow and underflow.

Now, the issue is with the error expression. Right now, for a given input, say x, the error expression has a pair of values (v1, v2), where v1 = x, and v2 = Ex, which is the error amount of x. Now, the issue is whether this is correct, that is, whether v1 should be = x or not. A very likely semantics for the pair (v1, v2) is v1 - v2 <= x <= v1 + v2, so we can actually pick any v1 such that this relation hold. I recommend this be formalized properly in our paper draft.

Now, all these are orthogonal to the issue that we need to include the path condition in the computation of the input error bounds, which is already done.

**Comment by Himeshi** [comment]
@domainexpert what I'm proposing in this issue is to have not only the numeric values but the symbolic values contain error as well. 

For an example in the simplest case, if there is path condition x < 1, then a shadow map will contain the expression x + ex < 1 where ex is the symbolic error of x. If the path condition involves computations of symbolic inputs, then we get the updated error using the error propagation equations already in place now.

I believe right now we don't maintain expressions with symbolic error for path conditions.

**Comment by domainexpert** [comment]
@Himeshi I agree there is a real issue here. There is a semantical discrepancy between `x` in the actual program and the `x` in the error expression.

**Comment by domainexpert** [comment]
So when `x < 1` is decided to be false by KLEE, that `x` is actually some `y - ey` or `y + ey`.
And in the error expression we are talking about `x +- ex`, which, to think about it, is not clear what it means wrt. the real `x` in the program. But this might be fine as a first approximation.

**Comment by Himeshi** [comment]
Yes, agreed.

**Comment by domainexpert** [comment]
@Himeshi It is best to use a common understanding for all program variable `x`, that is the "erroneous" `x`, in other words, `x` that contains error. If we use `x + ex < 1` to constrain error expression for condition `x < 1` in the program, then as explained, 
1. This severs the relation between `x` in the program and `x` in the error expression: They have no relationship anymore.
2. The meaning of `x` in the error expression is no longer clear.

I propose the following resolution: Let us assume that the meaning of `x` is the "erroneous" `x` everywhere. That means, it is always understood that `x` is the `x` that contains error. Hence, `x` has the same meaning in the program and in the error expression. I think this is also commonly adopted in the literature. So, for the error expression, only `x < 1` needs to be added to it to constrain the `x` in it, instead of `x + ex < 1`, since the meaning of `x` in this constraint is unclear (at least to me).

**Comment by domainexpert** [comment]
@Himeshi Just for the record that we assumed that the variables of the program and the variables of the error expressions are different: The variables of the error expression are the exact real number value. Hence, indeed the constraint `x + ex < 1` should be added to constraint the error expression.

**Comment by Himeshi** [comment]
Solved with PR #56
